app:
  datasourse:
    jdbc-url: jdbc:postgresql://fudidoseamigos.servegame.com:5432/bd_idk
    schema: Eldoom
    username: BDAdmin
    password: admin
    pool-size: 10
    connectionTimeout: 60000 
    idleTimeout: 300000 
    maxLifetime: 1800000 
